baseURL = "https://bunnyislewd.com/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"

title = "Bunnyislewd adult online content creator"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]
#favicon = false
favicon = "favicon.ico"

[params.author]
   name = "Bunnyislewd"
   headline = "18+ camslut and content creator"
   image = "images/frontal.jpg"  # path relative to static directory

#  { link = { href = "https://github.com/jpanther/lynx/blob/stable/README.md", text = "View the readme", icon = "github" } },
#  { link = { href = "styles/", text = "All the link styles", target = "_self" } },
  links = [
     { link = { href = "https://cash.app/$BunnyisLewd", text = "Cashapp", icon = "cashapp" } },
     { twitter  = { href = "https://x.com/bunnyisnude", text = "Private Twitter ($15 via Cashapp)", icon = "Twitter" } },
     { twitter = { href = "https://twitter.com/bunnyislewd", text = "Public Twitter", icon = "Twitter" } },
     { amazon = { href = "https://throne.com/bunnyislewd", text = "Throne Wishlist", icon = "gift" } },
     { link = { href = "https://onlyfans.com/bunnyislewd", text = "Onlyfans", icon = "onlyfans" } },
     { link = { href = "https://fansly.com/bunnyislewd", text = "Fansly", icon = "" } },
     { link = { href = "https://chaturbate.com/bunnyislewd", text = "Chaturbate", icon = "" } },
     { snapchat = "https://snapchat.com/add/bunnyislewd" },
     { link = { href = "https://www.manyvids.com/Feed/bunnyislewd/1003105966", text = "Manyvids", icon = "" } },
     { amazon = { href = "https://www.amazon.com/hz/wishlist/ls/3R9Y9JHL2K0QD", text = "Stream room renovations/recovery wishlist", icon = "gifts" } },
    # { link = "https://link-to-some-website.com/" },
    { amazon = "https://www.amazon.com/hz/wishlist/ls/BK7MD246AJAV" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    # { bluesky = "" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "" },
    # { gitlab = "" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "" },
    # { mastodon = "" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },

    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "" },
    # { tumblr = "https://username.tumblr.com" },
     { twitch = "https://twitch.tv/bunnyisgaming" },
     { bluesky = "https://bsky.app/profile/bunnyislewd.bsky.social" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "" },
    # { youtube = "" },
    { email = "mailto:bunnyislewd@outlook.com" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
