baseURL = "https://links.joshuacasey.net/"
languageCode = "en"
defaultContentLanguage = "en"

title = "links.joshuacasey.net"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "Joshua Casey"
   headline = "Online Activist & Video Game Streamer"
  # image = "img/author.jpg"  # path relative to static directory

  links = [
     { email = "mailto:contact@joshuacasey.net" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
     { bluesky = "https://bsky.app/profile/joshuacasey.net" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
     { discord = "https://discord.gg/38JUvfDpMt" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/JoshuaACasey" },
     { gitlab = "https://gitlab.com/JoshuaACasey" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
     { linkedin = "https://linkedin.com/in/joshuaacasey" },
     { mastodon = "https://aethy.com/@Nerd_JAC" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
     { steam = "https://steamcommunity.com/id/JoshuaACasey" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
     { tiktok = "https://tiktok.com/@JoshuaACasey" },
    # { tumblr = "https://username.tumblr.com" },
     { twitch = "https://twitch.tv/JoshuaACasey" },
     { twitter = "https://twitter.com/Nerd_JAC" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/Nerd_JAC" },
     { youtube = "https://www.youtube.com/c/JoshuaCasey" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
